### ISSUE TITLE
Numbers items not aligned with Waveforms in WaveformView

### ISSUE THREAD

**Issue by yger** [kwikteam/phy-contrib#35]
Because the bug is still here in fact, and even if I mentioned it before, I create a separate issue to keep track of it. It can already be seen with 252 channels

![gui](https://cloud.githubusercontent.com/assets/1672447/14489833/acaa06d6-016f-11e6-99c5-91edf3f58efd.png)

The problem seems to be that when changing the ranges with Ctrl+ arrows, the numbers are not aligned anymore with the channels. This is annoying because after, when Zoom on channel is activated, the GUI zoom on the number and not on the channel when switching clusters...

**Comment by rossant** [comment]
In order to fully reproduce this, it would be great if you could send me the unwhitened templates as a npy file.

**Comment by yger** [comment]
Ok, I'll send you that asap. But even if you have smaller datasets (the old 252 channels I gave you), the error is always there. This is just stressed when you have more channels

**Comment by rossant** [comment]
is this fixed in https://github.com/kwikteam/phy/pull/693 ?

**Comment by yger** [comment]
I would say no: I can still see a large mismatch in the positions. I guess this is dependent of the scaling? Do you see the problem as solved you, on the large dataset I sent you? In fact, this problem is also there for 252 channels. This is not a top priority issue, but this is there

**Comment by rossant** [comment]
This is what I see:

![capture du 2016-04-14 15 17 52](https://cloud.githubusercontent.com/assets/1942359/14529290/1765e226-0254-11e6-9a99-10701f82b4ba.png)

The scaling is the following (in `~/.phy/TemplateGUI/state.json`):

```json
  "WaveformView0": {
    "box_scaling": [
      0.4240976183724846,
      0.043056764313424443
    ],
    "do_show_labels": true,
    "do_zoom_on_channels": true,
    "overlap": false,
    "probe_scaling": [
      1.0,
      1.0
    ]
  }
```

**Comment by rossant** [comment]
Did you erase `.phy` in your data directory?

**Comment by yger** [comment]
I did, but this is still not working. However, I don't have at all the same
settings in the .json file

"WaveformView0": {
    "box_scaling": [
      1.0,
      41.144777789250973
    ],
    "do_show_labels": true,
    "do_zoom_on_channels": true,
    "overlap": false,
    "probe_scaling": [
      1.0,
      1.0
    ]
  },

I'll try copy and paste yours. In any cases, if this is working for you,
this should work here too

2016-04-14 15:19 GMT+02:00 Cyrille Rossant <notifications@github.com>:

**Comment by nsteinme** [comment]
Cyrille, it might again relate to whether one used the mouse or the
keyboard shortcuts to do the zooming? They are redundant to at least some
extent.

**Comment by rossant** [comment]
@nsteinme I'm not sure it's related. What I suggest to do is always use the default pan/zoom settings (by pressing R) when fine-tuning the probe scaling with the keyboard. Once you're satisfied with the scaling, you can pan/zoom

**Comment by rossant** [comment]
> I'll try copy and paste yours. In any cases, if this is working for you,
> this should work here too

@yger did it work?

**Comment by yger** [comment]
Yes, this has solve the issue, numbers are now aligned.

Thanks

Pierre

2016-06-30 4:42 GMT+09:00 Cyrille Rossant <notifications@github.com>:
